from typing import Protocol
from app.models import Chunk, Document


class Repository(Protocol):
    def list_documents(self) -> list[Document]: ...
    def get_document(self, document_id: str) -> Document | None: ...
    def save_document(self, document: Document) -> None: ...
    def save_pdf(self, document_id: str, content: bytes) -> None: ...
    def read_pdf(self, document_id: str) -> bytes: ...
    def save_chunks(self, chunks: list[Chunk]) -> None: ...
    def search(self, vector: list[float], limit: int, threshold: float) -> list[Chunk]: ...
    def delete(self, document_id: str) -> None: ...
